#!/usr/bin/env python3
"""
Find exporter-flattened B-spline surfaces whose control net is generated by
repeated rigid motion.

This is intentionally semantic-agnostic. A hit can be:
  * translation   -> extrusion-like sweep
  * rotation      -> revolution-like sweep
  * screw         -> helical/thread-like sweep

The detector operates directly on STEP control points/weights and does not use
OCCT. It fits one SE(3) transform that maps every control point at sweep index
j to j+stride, across every track in the orthogonal parameter direction.
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import json
import math
import pathlib
import re
import sys
from dataclasses import dataclass

import numpy as np

ENTITY_RE = re.compile(r"^#(\d+)=(.*);$")
POINT_RE = re.compile(r"CARTESIAN_POINT\('[^']*',\(([^)]*)\)\)")
REF_RE = re.compile(r"#(\d+)")
COMPLEX_SURFACE_RE = re.compile(r"B_SPLINE_SURFACE\((\d+),(\d+),")
SIMPLE_SURFACE_RE = re.compile(r"B_SPLINE_SURFACE_WITH_KNOTS\('[^']*',(\d+),(\d+),")
RATIONAL_MARKER = "RATIONAL_B_SPLINE_SURFACE("


def compact_step_syntax(text: str) -> str:
    """Remove insignificant STEP whitespace while preserving quoted strings."""
    # STEP escapes an apostrophe as two apostrophes. Splitting on every quote
    # still preserves outside/inside parity because an escaped quote toggles
    # twice. Keep quoted chunks verbatim and strip whitespace from the rest.
    parts = text.split("'")
    for i in range(0, len(parts), 2):
        parts[i] = "".join(parts[i].split())
    return "'".join(parts)


def unquoted_semicolon(text: str) -> int | None:
    # Normally there is exactly one semicolon, at record end. str.find/count
    # stay in C and are dramatically faster than walking large raw STEP files
    # character-by-character. Doubled STEP quotes contribute two to the count,
    # so quote parity remains correct.
    start = 0
    while True:
        idx = text.find(";", start)
        if idx < 0:
            return None
        if text.count("'", 0, idx) % 2 == 0:
            return idx
        start = idx + 1


def iter_step_entities(path: pathlib.Path):
    """Yield (id, compact body) from one-line or multiline Part 21 files."""
    pending = ""
    start_re = re.compile(r"#\s*\d+\s*=")
    with path.open(errors="replace") as stream:
        for line in stream:
            pending += line
            while True:
                match = start_re.search(pending)
                if match is None:
                    # Header text cannot begin an entity; keep only a tiny suffix
                    # in case '#123=' was split at an unusual line boundary.
                    pending = pending[-64:]
                    break
                if match.start():
                    pending = pending[match.start():]
                end = unquoted_semicolon(pending)
                if end is None:
                    break
                record = compact_step_syntax(pending[: end + 1])
                pending = pending[end + 1 :]
                entity = ENTITY_RE.match(record)
                if entity is not None:
                    yield int(entity.group(1)), entity.group(2)


@dataclass
class Surface:
    entity_id: int
    u_degree: int
    v_degree: int
    grid: list[list[int]]
    weights: list[list[float]]
    rational: bool
    parents: list[int]


def balanced_segment(text: str, start: int) -> tuple[str, int]:
    if start >= len(text) or text[start] != "(":
        raise ValueError("expected '('")
    depth = 0
    quoted = False
    i = start
    while i < len(text):
        ch = text[i]
        if ch == "'":
            if quoted and i + 1 < len(text) and text[i + 1] == "'":
                i += 2
                continue
            quoted = not quoted
        elif not quoted:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
                if depth == 0:
                    return text[start : i + 1], i + 1
        i += 1
    raise ValueError("unbalanced parentheses")


def parse_ref_grid(segment: str) -> list[list[int]] | None:
    rows = re.findall(r"\((#[0-9]+(?:,#[0-9]+)*)\)", segment)
    if not rows:
        return None
    grid = [[int(x[1:]) for x in row.split(",")] for row in rows]
    width = len(grid[0])
    if width == 0 or any(len(row) != width for row in grid):
        return None
    return grid


def parse_float_grid(segment: str) -> list[list[float]] | None:
    rows = re.findall(r"\(([^()]*)\)", segment)
    out = []
    for row in rows:
        try:
            vals = [float(x) for x in row.split(",") if x]
        except ValueError:
            continue
        if vals:
            out.append(vals)
    if not out:
        return None
    width = len(out[0])
    if width == 0 or any(len(row) != width for row in out):
        return None
    return out


def parse_surface(entity_id: int, body: str, parents: list[int]) -> Surface | None:
    rational = RATIONAL_MARKER in body
    if rational:
        match = COMPLEX_SURFACE_RE.search(body)
    else:
        match = SIMPLE_SURFACE_RE.search(body)
    if match is None:
        return None

    u_degree, v_degree = map(int, match.groups())
    grid_start = match.end()
    if grid_start >= len(body) or body[grid_start] != "(":
        return None
    try:
        grid_segment, _ = balanced_segment(body, grid_start)
    except ValueError:
        return None
    grid = parse_ref_grid(grid_segment)
    if grid is None:
        return None

    if rational:
        marker = body.find(RATIONAL_MARKER)
        if marker < 0:
            return None
        weight_start = marker + len(RATIONAL_MARKER)
        if weight_start >= len(body) or body[weight_start] != "(":
            return None
        try:
            weight_segment, _ = balanced_segment(body, weight_start)
        except ValueError:
            return None
        weights = parse_float_grid(weight_segment)
        if weights is None:
            return None
        # The outer list itself is not captured by parse_float_grid, so rows are direct.
        if len(weights) != len(grid) or any(len(a) != len(b) for a, b in zip(weights, grid)):
            return None
    else:
        weights = [[1.0] * len(row) for row in grid]

    return Surface(
        entity_id=entity_id,
        u_degree=u_degree,
        v_degree=v_degree,
        grid=grid,
        weights=weights,
        rational=rational,
        parents=parents,
    )


def kabsch(src: np.ndarray, dst: np.ndarray) -> tuple[np.ndarray, np.ndarray, float, float]:
    src_mean = src.mean(axis=0)
    dst_mean = dst.mean(axis=0)
    x = src - src_mean
    y = dst - dst_mean
    h = x.T @ y
    u, _, vt = np.linalg.svd(h)
    r = vt.T @ u.T
    if np.linalg.det(r) < 0:
        vt[-1, :] *= -1
        r = vt.T @ u.T
    t = dst_mean - r @ src_mean
    residual = np.linalg.norm((src @ r.T + t) - dst, axis=1)
    return r, t, float(residual.max(initial=0.0)), float(np.sqrt(np.mean(residual * residual)))


def canonical_vector(v: np.ndarray) -> np.ndarray:
    v = v / np.linalg.norm(v)
    for x in v:
        if abs(float(x)) > 1e-12:
            return -v if x < 0 else v
    return v


def rotation_axis(r: np.ndarray) -> np.ndarray:
    values, vectors = np.linalg.eig(r)
    idx = int(np.argmin(np.abs(values - 1.0)))
    axis = np.real(vectors[:, idx])
    return canonical_vector(axis)


def rigid_motion_details(r: np.ndarray, t: np.ndarray, angle_eps: float, linear_eps: float) -> dict:
    cos_angle = max(-1.0, min(1.0, (float(np.trace(r)) - 1.0) * 0.5))
    angle = math.acos(cos_angle)
    if angle <= angle_eps:
        travel = float(np.linalg.norm(t))
        return {
            "kind": "translation" if travel > linear_eps else "identity",
            "translation": t.tolist(),
            "travel": travel,
            "rotation_deg": math.degrees(angle),
        }

    axis = rotation_axis(r)
    advance = float(np.dot(t, axis))
    # Solve (I-R)c = t - advance*axis, fixing c perpendicular to axis.
    a = np.vstack((np.eye(3) - r, axis.reshape(1, 3)))
    b = np.concatenate((t - advance * axis, [0.0]))
    center, *_ = np.linalg.lstsq(a, b, rcond=None)
    kind = "rotation" if abs(advance) <= linear_eps else "screw"
    turns_per_step = angle / (2.0 * math.pi)
    steps_per_turn = 1.0 / turns_per_step
    pitch = advance * steps_per_turn
    nearest_steps = round(steps_per_turn)
    rational_turn = (
        nearest_steps
        if nearest_steps > 0 and abs(steps_per_turn - nearest_steps) <= 1e-7
        else None
    )
    return {
        "kind": kind,
        "axis": axis.tolist(),
        "axis_point": center.tolist(),
        "rotation_deg": math.degrees(angle),
        "advance_per_step": advance,
        "pitch_per_turn": pitch,
        "steps_per_turn": steps_per_turn,
        "integer_steps_per_turn": rational_turn,
        "translation": t.tolist(),
    }


def oriented_grid(surface: Surface, direction: str):
    if direction == "v":
        tracks = surface.grid
        weights = surface.weights
        degree = surface.v_degree
    else:
        tracks = [list(col) for col in zip(*surface.grid)]
        weights = [list(col) for col in zip(*surface.weights)]
        degree = surface.u_degree
    return tracks, weights, degree


def normalized_weights(values: list[float]) -> np.ndarray | None:
    arr = np.asarray(values, dtype=float)
    nz = np.flatnonzero(np.abs(arr) > 1e-15)
    if len(nz) == 0:
        return None
    return arr / arr[nz[0]]


def similarity_fit(
    src: np.ndarray, dst: np.ndarray
) -> tuple[float, np.ndarray, np.ndarray, float, float] | None:
    src_mean = src.mean(axis=0)
    dst_mean = dst.mean(axis=0)
    x = src - src_mean
    y = dst - dst_mean
    denom = float(np.sum(x * x))
    if denom <= 1e-24:
        return None
    h = x.T @ y
    u, singular, vt = np.linalg.svd(h)
    sign = np.ones(3)
    if np.linalg.det(vt.T @ u.T) < 0:
        sign[-1] = -1.0
    r = vt.T @ np.diag(sign) @ u.T
    scale = float(np.dot(singular, sign) / denom)
    if not math.isfinite(scale) or scale <= 0:
        return None
    t = dst_mean - scale * (r @ src_mean)
    residual = np.linalg.norm((scale * (src @ r.T) + t) - dst, axis=1)
    return (
        scale,
        r,
        t,
        float(residual.max(initial=0.0)),
        float(np.sqrt(np.mean(residual * residual))),
    )


def similarity_signature(
    surface: Surface,
    direction: str,
    points: dict[int, np.ndarray],
) -> str | None:
    ordered_ids = [point_id for row in surface.grid for point_id in row]
    values = [points.get(point_id) for point_id in ordered_ids]
    if any(value is None for value in values):
        return None
    xyz = np.asarray(values, dtype=float)
    distances = []
    max_distance = 0.0
    for i in range(len(xyz)):
        for j in range(i + 1, len(xyz)):
            d = float(np.linalg.norm(xyz[i] - xyz[j]))
            distances.append(d)
            max_distance = max(max_distance, d)
    if max_distance <= 1e-15:
        return None
    normalized_distances = [round(d / max_distance, 9) for d in distances]

    flat_weights = [weight for row in surface.weights for weight in row]
    nz = next((abs(w) for w in flat_weights if abs(w) > 1e-15), None)
    if nz is None:
        return None
    normalized_weights = [round(w / nz, 9) for w in flat_weights]
    payload = repr(
        (
            surface.u_degree,
            surface.v_degree,
            len(surface.grid),
            len(surface.grid[0]),
            direction,
            tuple(normalized_distances),
            tuple(normalized_weights),
        )
    ).encode()
    return hashlib.sha256(payload).hexdigest()[:24]


def detect_profile_section_sweep(
    surface: Surface,
    direction: str,
    points: dict[int, np.ndarray],
    tolerance: float,
    weight_tol: float,
    min_sections: int = 4,
) -> dict | None:
    tracks, weights, _ = oriented_grid(surface, direction)
    sweep_len = len(tracks[0])
    if len(tracks) < 3 or sweep_len < min_sections:
        return None
    if any(len(track) != sweep_len for track in tracks):
        return None

    base_values = [points.get(track[0]) for track in tracks]
    if any(value is None for value in base_values):
        return None
    base = np.asarray(base_values, dtype=float)
    if base.shape != (len(tracks), 3):
        return None
    base_weights = normalized_weights([w[0] for w in weights])
    if base_weights is None:
        return None

    rigid_transforms = []
    rigid_max = 0.0
    similarity_transforms = []
    similarity_max = 0.0
    all_rigid = True
    for section in range(sweep_len):
        section_weights = normalized_weights([w[section] for w in weights])
        if section_weights is None or np.max(np.abs(section_weights - base_weights)) > weight_tol:
            return None
        dst_values = [points.get(track[section]) for track in tracks]
        if any(value is None for value in dst_values):
            return None
        dst = np.asarray(dst_values, dtype=float)

        r, t, max_residual, rms_residual = kabsch(base, dst)
        rigid_max = max(rigid_max, max_residual)
        rigid_transforms.append((r, t, rms_residual))
        if max_residual > tolerance:
            all_rigid = False

        sim = similarity_fit(base, dst)
        if sim is None:
            return None
        scale, sr, st, smax, srms = sim
        similarity_max = max(similarity_max, smax)
        similarity_transforms.append((scale, sr, st, srms))

    if all_rigid:
        kind = "rigid_profile_sweep"
        scales = [1.0] * sweep_len
        max_residual = rigid_max
    elif similarity_max <= tolerance:
        kind = "similarity_profile_sweep"
        scales = [item[0] for item in similarity_transforms]
        max_residual = similarity_max
    else:
        return None

    signature = similarity_signature(surface, direction, points)
    return {
        "surface": surface.entity_id,
        "parents": surface.parents,
        "rational": surface.rational,
        "u_degree": surface.u_degree,
        "v_degree": surface.v_degree,
        "direction": direction,
        "kind": kind,
        "profile_points": len(tracks),
        "sections": sweep_len,
        "scales": scales,
        "scale_min": min(scales),
        "scale_max": max(scales),
        "similarity_signature": signature,
        "max_residual": max_residual,
    }


def fit_stride(
    surface: Surface,
    direction: str,
    stride: int,
    points: dict[int, np.ndarray],
    weight_tol: float,
):
    tracks, weights, degree = oriented_grid(surface, direction)
    sweep_len = len(tracks[0])
    if sweep_len <= stride:
        return None
    if any(len(track) != sweep_len for track in tracks):
        return None

    src = []
    dst = []
    for track, wtrack in zip(tracks, weights):
        for j in range(sweep_len - stride):
            if abs(wtrack[j] - wtrack[j + stride]) > weight_tol:
                return None
            a = points.get(track[j])
            b = points.get(track[j + stride])
            if a is None or b is None:
                return None
            src.append(a)
            dst.append(b)
    if len(src) < 6:
        return None
    src = np.asarray(src, dtype=float)
    dst = np.asarray(dst, dtype=float)
    r, t, max_residual, rms_residual = kabsch(src, dst)
    return {
        "degree": degree,
        "tracks": len(tracks),
        "sweep_len": sweep_len,
        "pairs": len(src),
        "rotation": r,
        "translation": t,
        "max_residual": max_residual,
        "rms_residual": rms_residual,
    }


def detect_surface(
    surface: Surface,
    points: dict[int, np.ndarray],
    tolerance: float,
    weight_tol: float,
    max_stride: int,
    min_repeats: int,
) -> list[dict]:
    hits = []
    for direction in ("u", "v"):
        tracks, _, _ = oriented_grid(surface, direction)
        sweep_len = len(tracks[0])
        if sweep_len < min_repeats + 1:
            continue

        best = None
        for stride in range(1, min(max_stride, sweep_len - min_repeats) + 1):
            fit = fit_stride(surface, direction, stride, points, weight_tol)
            if fit is None or fit["max_residual"] > tolerance:
                continue

            motion = rigid_motion_details(
                fit["rotation"],
                fit["translation"],
                angle_eps=1e-8,
                linear_eps=tolerance,
            )
            if motion["kind"] == "identity":
                continue

            # Number of applications actually witnessed in the control net.
            applications = (sweep_len - 1) / stride
            if applications < min_repeats:
                continue

            record = {
                "surface": surface.entity_id,
                "parents": surface.parents,
                "rational": surface.rational,
                "u_degree": surface.u_degree,
                "v_degree": surface.v_degree,
                "direction": direction,
                "stride": stride,
                "tracks": fit["tracks"],
                "sweep_len": sweep_len,
                "applications": applications,
                "pairs": fit["pairs"],
                "max_residual": fit["max_residual"],
                "rms_residual": fit["rms_residual"],
                **motion,
            }
            # Smallest exact stride is the most useful fundamental generator.
            best = record
            break
        if best is not None:
            hits.append(best)
    return hits


def summarize(hits: list[dict], profile_sweeps: list[dict], exact_tolerance: float) -> dict:
    by_kind = collections.Counter(hit["kind"] for hit in hits)
    by_direction = collections.Counter(hit["direction"] for hit in hits)
    profile_by_kind = collections.Counter(hit["kind"] for hit in profile_sweeps)
    family_counts = collections.Counter(
        hit["similarity_signature"]
        for hit in profile_sweeps
        if hit.get("similarity_signature")
    )
    representatives = {}
    for hit in profile_sweeps:
        signature = hit.get("similarity_signature")
        if signature and signature not in representatives:
            representatives[signature] = hit
    profile_families = []
    for signature, count in family_counts.most_common(30):
        rep = representatives[signature]
        profile_families.append(
            {
                "signature": signature,
                "count": count,
                "representative_surface": rep["surface"],
                "direction": rep["direction"],
                "kind": rep["kind"],
                "u_degree": rep["u_degree"],
                "v_degree": rep["v_degree"],
                "profile_points": rep["profile_points"],
                "sections": rep["sections"],
                "scale_min": rep["scale_min"],
                "scale_max": rep["scale_max"],
            }
        )
    screw = [h for h in hits if h["kind"] == "screw"]
    rotations = [h for h in hits if h["kind"] == "rotation"]
    translations = [h for h in hits if h["kind"] == "translation"]
    exact_periodic = [h for h in hits if h["max_residual"] <= exact_tolerance]
    exact_profiles = [h for h in profile_sweeps if h["max_residual"] <= exact_tolerance]
    def sample_ids(items):
        ids = [h["surface"] for h in items]
        return {"count": len(ids), "sample": ids[:50], "truncated": len(ids) > 50}
    return {
        "periodic_rigid_hits": len(hits),
        "periodic_source_exact_hits": len(exact_periodic),
        "periodic_by_kind": dict(by_kind),
        "periodic_by_direction": dict(by_direction),
        "profile_sweep_hits": len(profile_sweeps),
        "profile_source_exact_hits": len(exact_profiles),
        "profile_by_kind": dict(profile_by_kind),
        "profile_family_count": len(family_counts),
        "top_profile_families": profile_families,
        "screw_surfaces": sample_ids(screw),
        "rotation_surfaces": sample_ids(rotations),
        "translation_surfaces": sample_ids(translations),
        "profile_sweep_surfaces": sample_ids(profile_sweeps),
        "max_periodic_residual": max((h["max_residual"] for h in hits), default=0.0),
        "max_profile_residual": max(
            (h["max_residual"] for h in profile_sweeps), default=0.0
        ),
    }


def analyze_file(path: pathlib.Path, args) -> dict:
    raw = {}
    types = {}
    points = {}
    inbound = collections.defaultdict(list)

    for entity_id, body in iter_step_entities(path):
        raw[entity_id] = body
        types[entity_id] = "COMPLEX" if body.startswith("(") else body.split("(", 1)[0]
        for ref in REF_RE.findall(body):
            inbound[int(ref)].append(entity_id)
        pm = POINT_RE.fullmatch(body)
        if pm is not None:
            xyz = tuple(float(x) for x in pm.group(1).split(","))
            if len(xyz) == 3:
                points[entity_id] = np.asarray(xyz, dtype=float)

    surfaces = []
    for entity_id, body in raw.items():
        if "B_SPLINE_SURFACE" not in body:
            continue
        parents = [p for p in inbound.get(entity_id, []) if types.get(p) == "ADVANCED_FACE"]
        surface = parse_surface(entity_id, body, parents)
        if surface is not None:
            surfaces.append(surface)

    hits = []
    profile_sweeps = []
    for surface in surfaces:
        hits.extend(
            detect_surface(
                surface,
                points,
                tolerance=args.tolerance,
                weight_tol=args.weight_tolerance,
                max_stride=args.max_stride,
                min_repeats=args.min_repeats,
            )
        )
        for direction in ("u", "v"):
            profile = detect_profile_section_sweep(
                surface,
                direction,
                points,
                tolerance=args.tolerance,
                weight_tol=args.weight_tolerance,
            )
            if profile is not None:
                profile_sweeps.append(profile)

    return {
        "input": str(path),
        "bytes": path.stat().st_size,
        "parsed_bspline_surfaces": len(surfaces),
        "summary": summarize(hits, profile_sweeps, args.source_exact_tolerance),
        "periodic_hits": hits,
        "profile_sweeps": profile_sweeps,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("paths", nargs="+")
    ap.add_argument("--tolerance", type=float, default=1e-9)
    ap.add_argument(
        "--source-exact-tolerance",
        type=float,
        default=1e-10,
        help="reporting threshold for source-exact candidates; does not widen detection",
    )
    ap.add_argument("--weight-tolerance", type=float, default=1e-10)
    ap.add_argument("--max-stride", type=int, default=24)
    ap.add_argument("--min-repeats", type=int, default=3)
    ap.add_argument("--summary-only", action="store_true")
    args = ap.parse_args()

    inputs = []
    for value in args.paths:
        path = pathlib.Path(value)
        if path.is_dir():
            inputs.extend(sorted(path.glob("*.step")))
        else:
            inputs.append(path)

    results = []
    for path in inputs:
        result = analyze_file(path, args)
        if args.summary_only:
            result.pop("periodic_hits", None)
            result.pop("profile_sweeps", None)
        results.append(result)
        print(
            f"{path}: {result['parsed_bspline_surfaces']} B-spline surfaces, "
            f"{result['summary']['periodic_rigid_hits']} periodic rigid sweeps "
            f"{result['summary']['periodic_by_kind']}, "
            f"{result['summary']['profile_sweep_hits']} profile sweeps "
            f"{result['summary']['profile_by_kind']}",
            file=sys.stderr,
        )

    print(json.dumps(results, indent=2, allow_nan=False))


if __name__ == "__main__":
    main()
